name: Auto Create Combined Release

on:
  push:
    branches: [ feature/auto-release ]

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install yq for YAML parsing
        run: |
          YQ_VERSION=v4.45.1
          wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64
          chmod +x /usr/local/bin/yq


      - name: Read major version and generate date-based minor version
        id: version
        run: |
          MAJOR=$(yq '.major' .release-config.yaml)
          DATE=$(date +%y%m%d)
          TIME=$(date +%H%M)
          echo "version=${MAJOR}.${DATE}.${TIME}" >> $GITHUB_OUTPUT

      - name: Prepare Slides Structure ZIP
        run: |
          mkdir -p slides-structure
          cp -r csl slides-structure/
          cp -r filters slides-structure/
          # cp -r highlight-styles slides-structure/
          cp justfile slides-structure/
          mkdir -p slides-structure/src/img
          cp src/*.md src/bibliography.bib slides-structure/src/
          cd slides-structure && zip -r ../slides-structure-${{ steps.version.outputs.version }}.zip .

      - name: Prepare AGHMD Beamer Theme ZIP
        run: |
          mkdir -p aghmd-beamer-theme
          cp -r AGHMD aghmd-beamer-theme/
          cd aghmd-beamer-theme && zip -r ../aghmd-beamer-theme-${{ steps.version.outputs.version }}.zip .

      - name: Create Git tag for combined release
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          TAG="combined-release-v${{ steps.version.outputs.version }}"
          git tag $TAG
          git push origin $TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release with both ZIPs
        uses: softprops/action-gh-release@v2
        with:
          name: "Combined Release - v${{ steps.version.outputs.version }}"
          tag_name: "combined-release-v${{ steps.version.outputs.version }}"
          files: |
            slides-structure-${{ steps.version.outputs.version }}.zip
            aghmd-beamer-theme-${{ steps.version.outputs.version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
