name: Auto Create Releases

on:
  push:
    branches: [ feature/auto-release ]

jobs:
  create-releases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install yq for YAML parsing
        run: |
          sudo apt-get update && sudo apt-get install -y yq

      - name: Read major version and generate date-based minor version
        id: version
        run: |
          MAJOR=$(yq '.major' .release-config.yaml)
          DATE=$(date +%Y%m%d)
          echo "version=${MAJOR}.${DATE}" >> $GITHUB_OUTPUT

      - name: Prepare Release 1
        run: |
          mkdir -p release-1
          cp -r csl release-1/
          cp -r filters release-1/
          # cp -r highlight-styles release-1/
          cp justfile release-1/
          mkdir -p release-1/src/img
          cp src/*.md src/bibliography.bib release-1/src/
          cd release-1 && zip -r ../release-1-${{ steps.version.outputs.version }}.zip .

      - name: Create Git tag for Release 1
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag release-1-v${{ steps.version.outputs.version }}
          git push origin release-1-v${{ steps.version.outputs.version }}

      - name: Create GitHub Release 1
        uses: softprops/action-gh-release@v2
        with:
          name: "Release 1 - v${{ steps.version.outputs.version }}"
          tag_name: "release-1-v${{ steps.version.outputs.version }}"
          files: release-1-${{ steps.version.outputs.version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for changes in AGHMD directory
        id: aghmd_check
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^AGHMD/'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Prepare and Zip Release 2 (AGHMD)
        # if: steps.aghmd_check.outputs.changed == 'true'
        run: |
          mkdir -p release-2
          cp -r AGHMD release-2/
          cd release-2 && zip -r ../release-2-${{ steps.version.outputs.version }}.zip .

      - name: Create Git tag for Release 2
        if: steps.aghmd_check.outputs.changed == 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag release-2-v${{ steps.version.outputs.version }}
          git push origin release-2-v${{ steps.version.outputs.version }}

      - name: Create GitHub Release 2
        if: steps.aghmd_check.outputs.changed == 'true'
        uses: softprops/action-gh-release@v2
        with:
          name: "Release 2 - v${{ steps.version.outputs.version }}"
          tag_name: "release-2-v${{ steps.version.outputs.version }}"
          files: release-2-${{ steps.version.outputs.version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
