name: Release README on Feature Branch

on:
  push:
    branches:
      - feature/auto-release

jobs:
  release-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate version based on date
        id: version
        run: |
          VERSION="test-$(date +%Y%m%d%H%M%S)"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag ${{ steps.version.outputs.version }}
          git push origin ${{ steps.version.outputs.version }}

      - name: Create GitHub Release with README.md
        uses: softprops/action-gh-release@v2
        with:
          name: "Test Release ${{ steps.version.outputs.version }}"
          tag_name: ${{ steps.version.outputs.version }}
          files: README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
